# Generated by Django 2.0.7 on 2018-07-06 00:24

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeFairModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id_file', models.IntegerField(unique=True)),
                ('longitude', models.BigIntegerField()),
                ('latitude', models.BigIntegerField()),
                ('setcens', models.BigIntegerField()),
                ('areap', models.BigIntegerField()),
                ('coddist', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
                ('codsubpref', models.IntegerField()),
                ('subpref', models.IntegerField()),
                ('region_five', models.CharField(max_length=15)),
                ('region_eigth', models.CharField(max_length=15)),
                ('name_fair', models.CharField(max_length=100)),
                ('register', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('neighborhood', models.CharField(max_length=50)),
                ('reference_point', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
