# Generated by Django 2.0.7 on 2018-07-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_free_fair', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freefairmodels',
            name='subpref',
            field=models.CharField(max_length=100),
        ),
    ]
